### ISSUE TITLE
Import contact par csv

### ISSUE THREAD

**Issue by Polysonnerie** [xech/agora-project#11]
Bonjour, 
Je souhaite importer des contacts dans mon espace en important un fichier csv. 
Quand je valide l'import, mon fichier est bien reconnu et les informations vont bien dans les bonnes colonnes 
![1er écran](https://user-images.githubusercontent.com/71062634/92691543-032f2080-f343-11ea-99e0-c7813692d75c.JPG)
mais quand je valide la 2ème fois, la fenêtre devient blanche et rien ne se passe.
![2ème écran](https://user-images.githubusercontent.com/71062634/92691683-38d40980-f343-11ea-8654-d8d5df93fcc2.JPG)

 Pouvez-vous m'expliquer ce bug et comment le résoudre s'il vous plait ?

**Comment by xech** [comment]
Bonjour,
Le soucis sera normalement corrigé avec la nouvelle version 3.7.3.1
Cordialement
Xech
