### ISSUE TITLE
Pb de redirection après suppression évènement quand vue multi-agenda

### ISSUE THREAD

**Issue by bleasyw** [xech/agora-project#12]
Dans la partie Agendas, lorsque plusieurs agendas partagés sont affichés et que le titulaire de l'un d'eux supprime un de ses évènements, l'affichage ne revient pas sur tous les agendas affichés à l'origine mais uniquement sur celui du titulaire. Il faut recocher tous les agendas pour les réafficher.

**Comment by xech** [comment]
Bonjour,
C'est désormais corrigé sur la dernière version 3.7.4.1
Bien à vous
Xech
