### ISSUE TITLE
Syntax error on MySQL 8.0

### ISSUE THREAD

**Issue by GaneshKandu** [xech/agora-project#13]
Hi,

I am getting an SQL error in agora 3.7.4.2 after login on MySQL 8.0

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ASC' at line 1

**Comment by xech** [comment]
Hello,
Have you tried the latest version 3.8.0 to see if this fixes your problem with MySql 8.0 ?
cordially

**Comment by GaneshKandu** [comment]
@xech
i tried but getting another issue 

```Fatal error: Call to a member function getLabel() on a non-object in app/Common/VueStructure.php on line 50 ```

**Comment by xech** [comment]
Hello, the application was indeed problematic with the version 8.0 of MySql. This should work with the latest version 3.8.0 of Agora-Project, which you can download now
