### ISSUE TITLE
Agora-Project version 3.8.0 throws Fatal error

### ISSUE THREAD

**Issue by prbt2016** [xech/agora-project#14]
Hello,

I was in the process of manual installation of Agora-Project version 3.8.0 on Centos 6.9 with PHP 5.5, MYSQL 5.5, Apache 2.2.34.

However, while starting the installation I get a blank page.

So to check further, I checked with Ctrl+U in the browser and it shows the error i.e :

`Fatal error: Call to a member function getLabel() on null in /{{PATH}}/{{TO}}/{{AGORA}}/app/Common/VueStructure.php on line 50 `

What could be the cause of this issue?. Could you please replicate the issue at your end and fix this?

**Comment by prbt2016** [comment]
Any updates regarding the same ?. Kindly let me know.

**Comment by xech** [comment]
Hello, there was indeed a problem here. This should work with the very latest version 3.8.0 , which you can download right now

**Comment by prbt2016** [comment]
Hello,

Thanks for looking into the issue. Shall check out with the latest zip.

Regards.

**Comment by prbt2016** [comment]
Hello,

Thanks for the fix. Now Agora 3.8.0 is working fine now.

Regards.

**Comment by xech** [comment]
very good, happy that things are working now
cordially
Xech

**Comment by atao60** [comment]
> This should work with the very latest version 3.8.0 , which you can download right now

Just take me some time to realize that `very latest version 3.8.0` doesn't refer to the [last release](https://github.com/xech/agora-project/tree/3.8.0) (i.e. based on commit  [#fd89e12](https://github.com/xech/agora-project/commit/fd89e127dee50f54623e81ec9985edb66c1253d5)) but on the "very last commit" [#0333de3](0333de369d3aec37a6933b3c3d8d8210209b0fa7).

To avoid any ambiguity, a true working release would be welcome.

By the way, thanks for this great project.
