### ISSUE TITLE
Notification par email de news: idle timeout.

### ISSUE THREAD

**Issue by tlatelolco** [xech/agora-project#18]
Bonjour,

lorsque je dois notifier par mail 157 destinataires de la création d’une nouvelle, j’obtiens le log d’erreur apache suivant:
> : [Mon Jun 28 12:05:05 2021] [error] [client 45.123.63.45] [host agora.website.com] AH10141: FastCGI: comm with server "/home/user/agora/index.php" aborted: idle timeout (160 sec), referer: https://agora.website.com/?ctrl=dashboard&targetObjId=dashboardNews-104&action=dashboardNewsEdit
> : [Mon Jun 28 12:05:05 2021] [error] [client 45.123.63.45] [host agora.website.com] AH10149: FastCGI: incomplete headers (0 bytes) received from server "/home/user/agora/index.php", referer: https://agora.website.com/?ctrl=dashboard&targetObjId=dashboardNews-104&action=dashboardNewsEdit  

J’ai créé un espace de test dans lequel je suis seul: je reçois bien l’e-mail de notification.

Est-il attendu que l’envoi de 157 destinataires doit prendre plus de 160 secondes et il y a un paramètre de l’hébergement à changer ou bien est-ce un bug du logiciel ?

Cordialement

**Comment by xech** [comment]
Bonjour,
Normalement l'envoie d'emails n'est pas problématique. Cela dépend surtout du paramétrage du "sendmail" sur votre serveur web. Si l'envoie d'email pose toujours soucis, vous pouvez toujours essayer de le configurer via le "paramétrage général" de  votre espace, dans les option "SMTP". Aussi, je vous invite à faire une mise à jour sur la version 21.10 d'Agora-Project !
Cordialement
Xech
