### ISSUE TITLE
Problème d'affichage Agenda

### ISSUE THREAD

**Issue by Hocine7500** [xech/agora-project#19]
Bonjour, 
Je viens d'installer Agora-projet sur mon vps, et je veux l'utiliser comme agenda partagé, le problème, c'est que je constate un bug au niveau de l'affichage par "semaine" et par "jour" en effet, lorsqu'en programme plus de 4 RDV sur le même créneau horaire, impossibles de les afficher en même temps et le seul moyen de les afficher c'est de changer la vue par mois.
Pourriez-vous m'aider à trouver une solution à cela s'il vous plait ? 
Ci-joint quelques photo du problème : 
-----
Hello, 
I just installed Agora-project on my vps, and I want to use it as a shared calendar, the problem is that I notice a bug in the display by "week" and by "day" indeed, when scheduling more than 4 appointments on the same time slot, impossible to display them at the same time and the only way to display them is to change the view by month.
Could you help me to find a solution to this please? 
Here are some pictures of the problem: 
![Cap11](https://user-images.githubusercontent.com/32882125/141454788-a55a0411-2450-488f-83aa-6e37018fc386.png)
![Cap12](https://user-images.githubusercontent.com/32882125/141454789-7b49e068-cb25-40ac-aecc-d2d2c89d13c8.png)

Dans l'attente de votre retour.

cordialement

Looking forward to your return.

Cordially,

**Comment by xech** [comment]
Merci pour ce retour,
Nous regarderons comment régler ce soucis d'affichage prochainement.
Cordialement
Xech

**Comment by ecrozier** [comment]
Merci pour tous ces correctifs !!
Excellent travail !!





Le Lundi, Avril 03, 2023 15:37 CEST, xech armenteros ***@***.***> a écrit:
 
 
Closed #19 as completed.
