### ISSUE TITLE
PDF and Password

### ISSUE THREAD

**Issue by ecrozier** [xech/agora-project#22]
![Pdf-motdepasse](https://user-images.githubusercontent.com/17794483/205511070-cfbe453e-4309-48a7-900b-e62f2d70bbdb.JPG)

Sorry but the release 22.12.0 ne résoud pas le problème de mot de passe associé au PDF.  !!!

**Comment by xech** [comment]
Bonjour à tous, 
Le problème a bien été réglé sur la toute prochaine version 23.4
Cdlt
Xech
