### ISSUE TITLE
PDF and Password (next)

### ISSUE THREAD

**Issue by ecrozier** [xech/agora-project#23]
Le mot de passe du document bloque une partie du logiciel comme le montrent les captures d'écran.
capture (2) doc. avec mot de passe (1ère dia)
capture (3) doc.  le même doc. sans mot de passe (2ème dia)
mais dans les deux cas le fichier choisi est correctement téléversé !!! merci de me faire un mot si solution pour éviter ce message d'erreur tout de même bien pénible !!

**Comment by xech** [comment]
Bonjour,
Le problème a bien été corrigé sur la prochaine version 23.4
Cdlt
Xech
