### ISSUE TITLE
Sécurité : en cas d'indisponibilité de la DB un panneau proposant l'installation est proposé 

### ISSUE THREAD

**Issue by Zeuh** [xech/agora-project#25]
Bonjour,

Lorsque la DB est indisponible (quelque soit la raison) et alors qu'une installation a déjà été effectuée, le site propose les panneaux d'installation / configuration. Cela peut potentiellement permettre une prise en main du site par une personne mal intentionnée.

Le comportement attendu : 
- quand une installation a déjà été effectuée, le panneau d'installation ne devrait plus jamais être proposé.
- lorsque la connexion à la DB est impossible, un message d'erreur annonçant l'indisponibilité devrait s'afficher.

https://github.com/xech/agora-project/blob/master/app/Common/Db.php#L36

Cordialement,

**Comment by xech** [comment]
Bonjour et merci pour ce retour,
Effectivement la prochaine mise à jour 23.4 permettra de clôturer l'accès à la page d'installation dans ce cas de figure.
Cdlt
Xech
