### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [xech/agora-project#26]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@cosad3s) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by xech** [comment]
Good morning,

A new SECURY.md file has just been created. In addition, the new version 23.4.1 corrects password hash issues : "pass the hash" and SHA1 hash algorithm in particular

Cordially
