### ISSUE TITLE
MySql 8.0 compat issue

### ISSUE THREAD

**Issue by mbautista** [xech/agora-project#3]
Hello,
I just installed Agora Projedct 3.6.3 on Debian 9 / Apache2 / PHP7 FPM / MySql 8.0.

I had a SQL error due to the "rank" field which is a reserved keyword in MySql 8.0.

It would be nice to escape the rank field with backticks to avoid this error.

Thank you :)

**Comment by xech** [comment]
Thank's for your contribution. A modification will be made in the next version, to avoid this "collision" with the keywords reserved by MySQL 8.0 +.
cordially
xech

**Comment by xech** [comment]
Hello, the new version 3.6.5 corrects this problem with some versions of MySQL
Cordially
Xech
