### ISSUE TITLE
Cross-site Scripting vulnerability

### ISSUE THREAD

**Issue by benharbone** [xech/agora-project#31]
hi all,

Can someone check security and apply correction please ?
- URL encoded GET input _idSpaceAccess was set to 4111111111111111%22onmouseover=qFtS(93592)%22
- URL encoded GET input action was set to <A HrEF=javascript:iRVl(9338);//http://>
- URL encoded GET input objUrl was set to http://www.example.com%22onmouseover=qFtS(90212)%22
- POST (multipart) input action was set to <A HrEF=javascript:LkFz(9554);//http://>
- ....
Thanks

**Comment by benharbone** [comment]
--- src/app/ModOffline/VueConnection.php
+++ rde/app/ModOffline/VueConnection.php
@@ -101,10 +101,10 @@
 
 		
 		<form action="index.php" method="post" id="formConnect">
-			<input type="text" name="connectLogin" value="<?= $defaultLogin ?>" placeholder="<?= Txt::trad("mailLlogin") ?>" title="<?= Txt::trad("mailLlogin") ?>">
-			<input type="password" name="connectPassword" value="<?= Req::param("newPassword") ?>" placeholder="<?= Txt::trad("password") ?>" title="<?= Txt::trad("password") ?>">
-			<input type="hidden" name="objUrl" value="<?= Req::param("objUrl") ?>">					
-			<input type="hidden" name="_idSpaceAccess" value="<?= Req::param("_idSpaceAccess") ?>">	
+			<input type="text" name="connectLogin" value="<?= htmlspecialchars($defaultLogin, ENT_QUOTES, 'UTF-8') ?>" placeholder="<?= Txt::trad("mailLlogin") ?>" title="<?= Txt::trad("mailLlogin") ?>">
+			<input type="password" name="connectPassword" value="<?= htmlspecialchars(Req::param("newPassword"), ENT_QUOTES, 'UTF-8') ?>" placeholder="<?= Txt::trad("password") ?>" title="<?= Txt::trad("password") ?>">
+			<input type="hidden" name="objUrl" value="<?= htmlspecialchars(Req::param("objUrl"), ENT_QUOTES, 'UTF-8') ?>">					
+			<input type="hidden" name="_idSpaceAccess" value="<?= htmlspecialchars(Req::param("_idSpaceAccess"), ENT_QUOTES, 'UTF-8') ?>">	
 			<button type="submit"><?= Txt::trad("connect") ?></button>
 			<div class="vConnectOptions">
 				<div><input type="checkbox" name="rememberMe" value="1" id="boxRememberMe" checked><label for="boxRememberMe" title="<?= Txt::trad("connectAutoTooltip") ?>"><?= Txt::trad("connectAuto") ?></label></div>

**Comment by xech** [comment]
Hi William!
What exactly is the vulnerability mentioned and does it also concern the latest version 24.4.5 ? Please provide more details on the context.
THANKS

**Comment by benharbone** [comment]
Hi, 
This is a Cross-site Scripting vulnerability identified by: 
--------------- 
URL encoded GET input _idSpaceAccess was set to 4111111111111111%22onmouseover=qFtS(93592)%22 
The input is reflected inside a tag parameter between double quotes. 
Request 
GET /php/? 
_idSpaceAccess=4111111111111111%22onmouseover=qFtS(93592)%22&objUrl=http://www.example.com&password= 
u]H[ww6KrA9F.x-F HTTP/1.1 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 
Accept-Encoding: gzip,deflate,br 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/121.0.0.0 Safari/537.36 
Connection: Keep-alive 
-------------- 
The vulnerabilities are identified in the variables passed in GET POST: 
- "URL encoded GET input _idSpaceAccess" 
- "URL encoded GET input action" 
- "URL encoded GET input objUrl" 

Example to solve: 
Req::isParam("_idSpaceAccess") 
replaced by 
htmlspecialchars(Req::isParam("_idSpaceAccess"), ENT_QUOTES, 'UTF-8') 

Req:isParam("objUrl") 
replaced by 
htmlspecialchars(Req::isParam("objUrl"), ENT_QUOTES, 'UTF-8') 

self::param("ctrl") 
replaced by 
htmlspecialchars(self::param("ctrl"), ENT_QUOTES, 'UTF-8') 

self::param("action") 
replaced by 
htmlspecialchars(self::param("action"), ENT_QUOTES, 'UTF-8') 

Req::param("login") 
replaced by 
htmlspecialchars(Req::param("login"), ENT_QUOTES, 'UTF-8') 

Req::param("credential") 
replaced by 
htmlspecialchars(Req::param("credential"), ENT_QUOTES, 'UTF-8') 

$defaultLogin 
replaced by 
htmlspecialchars($defaultLogin, ENT_QUOTES, 'UTF-8') 

Req::param("newPassword") 
replaced by 
htmlspecialchars(Req::param("newPassword"), ENT_QUOTES, 'UTF-8') 

Req::param("resetPasswordMail") 
replaced by 
htmlspecialchars(Req::param("resetPasswordMail"), ENT_QUOTES, 'UTF-8') 

Req::isParam("_idInvitation") 
replaced by 
htmlspecialchars(Req::isParam("_idInvitation"), ENT_QUOTES, 'UTF-8') 

it's a temporary resolution which can be improved, but which is certainly not the most adapted to the code. 
Thank you in any case for your contribution. 
I don't believe this is fixed in the latest version 

Just check your website with "Acunetix" [ https://www.acunetix.com/plp/web-vulnerability-scanner/ | https://www.acunetix.com/plp/web-vulnerability-scanner/ ]

**Comment by benharbone** [comment]
Recommendation
Apply context-dependent encoding and/or validation to user input rendered on a page
References
Cross-site Scripting (XSS) Attack - Acunetix
https://www.acunetix.com/websitesecurity/cross-site-scripting/
Types of XSS - Acunetix
https://www.acunetix.com/websitesecurity/xss/
XSS Filter Evasion Cheat Sheet
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
Excess XSS, a comprehensive tutorial on cross-site scripting

**Comment by xech** [comment]
Hello Ben,
With the new version 24.6.0 the vulnerabilities have been fixed.
Thanks again for your contribution!
Xech
