### ISSUE TITLE
Agora-Project Upgarde Issue 24.61

### ISSUE THREAD

**Issue by pinalgirkar** [xech/agora-project#33]
I tried to update the Agora-Project 24.6.1, I installed the zip  from (https://www.agora-project.net/index.php?ctrl=offline&action=download) and I deleted the "app", "doc" and "index.php" of the older version 24.6.0 and upload the new zip file and folder and visited the installation via browser and the following error was thrown

![image](https://github.com/xech/agora-project/assets/106646072/186eed62-1e31-414b-a744-27cc5f708892)

Can you please look over the issue and do the needful.

Thanks

**Comment by xech** [comment]
You can try the new version 24.6.2 which should correct the update problem.
Sincerely
