### ISSUE TITLE
PHP 8.0+ compatibility?

### ISSUE THREAD

**Issue by orhtej2** [xech/agora-project#34]
I tried running Agora on PHP 8.3 and noticed that `File::getBytesSize` displays inconsistent behaviour in PHP 7.4 vs PHP 8.0+;

With input `go` it returns 0 in 7.4 and runtime error in 8.0 because of [difference in integer strings handling](https://www.php.net/manual/en/language.types.numeric-strings.php).

While this was ultimately caused by user error, is the code battle proven against newer PHP versions? [8.1](https://www.php.net/supported-versions.php) is the lowest officially supported version right now.

**Comment by xech** [comment]
Hi!
The upcoming version 24.11 will fix this issue with the "File::getBytesSize()" function.
In the meantime, you can fix this by replacing the function with the following code :

```
	public static function getBytesSize($sizeText)
	{
		if(preg_match("/(g|go)$/i",$sizeText))		{return floatval(str_ireplace(["go","g"],"",$sizeText)) * self::sizeGo;}
		elseif(preg_match("/(m|mo)$/i",$sizeText))	{return floatval(str_ireplace(["mo","m"],"",$sizeText)) * self::sizeMo;}
		elseif(preg_match("/(k|ko)$/i",$sizeText))	{return floatval(str_ireplace(["ko","k"],"",$sizeText)) * self::sizeKo;}
		else										{return $sizeText;}
	}
```

**Comment by xech** [comment]
Note : the very next version is on the way :)

**Comment by xech** [comment]
Note : the very next version is on the way :)
