### ISSUE TITLE
Soucis de dépôts de fichiers pour la mairie de Mozac.

### ISSUE THREAD

**Issue by enguerr** [xech/agora-project#4]
Bonjour,
Auriez-vous un service de support pour votre logiciel Agora Omnispace ?
Nous avons quelques soucis avec un client commun .

Merci d'avance.

**Comment by xech** [comment]
Bonjour,
Suite à notre échange par email, je vous informe que des modifications ont été apportées sur la dernière version 3.6.4 concernant le dépôt/upload de fichiers. Par ailleurs, vous devriez voir en détails la procédure de mise à jour et d'installation dans le fichier "DOCUMENTATION_FR.pdf" : il se trouve dans le dossier "/docs" et donne quelques indications notamment sur le paramétrage du fichier "php.ini".
Cordialement
xech
