### ISSUE TITLE
Getting error in Agora-Project 3.6.5

### ISSUE THREAD

**Issue by GaneshKandu** [xech/agora-project#5]
Hi,

I am getting error after login in Agora-Project 3.6.5

'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'publicVote' in 'group statement'' in app/Common/Db.php:68

```
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'publicVote' in 'group statement'' in app/Common/Db.php:68
Stack trace:
#0 app/Common/Db.php(68): PDO->query('SELECT T1.*, CO...')
#1 app/ModDashboard/MdlDashboardPoll.php(46): Db::getObjTab('dashboardPoll', 'SELECT T1.*, CO...')
#2 app/ModDashboard/CtrlDashboard.php(33): MdlDashboardPoll::getPolls('list', 0, true, true)
#3 app/Common/Req.php(62): CtrlDashboard::actionDefault()
#4 index.php(10): Req->__construct()
#5 {main}
```

System Details

| |version|
| --- | --- |
|MySQL|5.5.60|
|PHP|5.5.38|

**Comment by xech** [comment]
Hello and thank you for this quick contribution. Indeed, during the first installation of Agora-Project v3.6.5, this field was not created. It's now settled, you can retry.
Have a good day
xech

**Comment by GaneshKandu** [comment]
Hi @xech 
Thanks working now :+1:
