### ISSUE TITLE
Add a module

### ISSUE THREAD

**Issue by narce293** [xech/agora-project#6]
HI thank you for this worderfull collaborative tool. I want to add a new module but i don't know how to do can you please help me ? the module will help users on agora to write theirs issues and get anwers from administrators only and only the user who post it can see it.thank you

**Comment by xech** [comment]
Hello. 
If you want to add a module, you can copy an existing module such as "modTask", and  simply adapt the code to your needs. Don't forget to add also your tables in the database, and edit the file '/ModOffline/db.sql', and add your module name in the file '/ModSpace/MdlSpace.php' (cf. $moduleList).
Have a good day
