### ISSUE TITLE
Fresh install with tag 3.6.5

### ISSUE THREAD

**Issue by bnu-siin** [xech/agora-project#7]
Hello, 

When installing from scratch agora v 3.6.5 using the git repos and the tag 3.6.5 we encounter some DB errors after the first login. 

The app/ModOffline/db.sql which is tagged 3.6.5 (commit 9c9e891cba4f1cd38c5ce2b605466fa518c1afa5) don't include the fix in 1abd891786684703d41ac2d2326111fa2afa4781 . 

Could you update the tag 3.6.5 with the fix. 
Thanks.

**Comment by fredmenez** [comment]
I ran into the issue, thinking the latest labelled version was the most trustable but in this case we are better off with the bleeding edge version :
```
git clone https://github.com/xech/agora-project.git
git checkout 3b724ce1b4860951f8973b2ec0349841e985c5d2
```

**Comment by xech** [comment]
Hello,
The new version 3.7.0 has just been released. It corrects your installation problems and brings many improvements: do not hesitate to test it!
cordially
