### ISSUE TITLE
Files greater than 150MB cannot be uploaded

### ISSUE THREAD

**Issue by Machiuka** [xech/agora-project#9]
Hello Agora Team,

Firstly I want to congratulate you for the awesome software that you kindly offer to us. I have a problem uploading large files (>150MB). I made all the settings on my Cpanel php dashboard to allow uploading of files up to 1GB. It starts uploading, but when it reach a certain percentage (never the same) it drops to 0% and the uploading process stops. I've tried to upload manually, I update the app_file and app_fileVersion tables and I rename the file with the name i put in the app_fileVersion respecting the naming logic of the files already uploaded, but it didn't show it on my files manager. Please advise me what to do.
Thank you!
Update: I find app_ObjectTarget table that must be filled, in order to complete the manual upload procedure. Still is very cumbersome to modify manually all those tables.

**Comment by xech** [comment]
It's depends on your PHP configuration. If it's possible, you just have to modify the "php.ini" file of your web server (often in "/etc/php7/apache2/php.ini"), and then modify the "post_max_size" and "upload_max_filesize" parameters to increase the size of the uploaded files. Finally restart your web server to apply the changes.
xech
